//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookstoreRef.Service.MyService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/BookstoreApp")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyService.IBookstoreService")]
    public interface IBookstoreService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookstoreService/GetData", ReplyAction="http://tempuri.org/IBookstoreService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookstoreService/GetData", ReplyAction="http://tempuri.org/IBookstoreService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookstoreService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IBookstoreService/GetDataUsingDataContractResponse")]
        BookstoreRef.Service.MyService.CompositeType GetDataUsingDataContract(BookstoreRef.Service.MyService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookstoreService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IBookstoreService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<BookstoreRef.Service.MyService.CompositeType> GetDataUsingDataContractAsync(BookstoreRef.Service.MyService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookstoreService/GetBooks", ReplyAction="http://tempuri.org/IBookstoreService/GetBooksResponse")]
        System.Collections.Generic.List<Bookstore.Interface.Book> GetBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookstoreService/GetBooks", ReplyAction="http://tempuri.org/IBookstoreService/GetBooksResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Bookstore.Interface.Book>> GetBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookstoreService/GetBookAsync", ReplyAction="http://tempuri.org/IBookstoreService/GetBookAsyncResponse")]
        System.Collections.Generic.List<Bookstore.Interface.Book> GetBookAsync(string searchString, string searchOn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookstoreService/GetBookAsync", ReplyAction="http://tempuri.org/IBookstoreService/GetBookAsyncResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Bookstore.Interface.Book>> GetBookAsyncAsync(string searchString, string searchOn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookstoreService/AddBook", ReplyAction="http://tempuri.org/IBookstoreService/AddBookResponse")]
        void AddBook(Bookstore.Interface.Book newBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookstoreService/AddBook", ReplyAction="http://tempuri.org/IBookstoreService/AddBookResponse")]
        System.Threading.Tasks.Task AddBookAsync(Bookstore.Interface.Book newBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookstoreService/UpdateBook", ReplyAction="http://tempuri.org/IBookstoreService/UpdateBookResponse")]
        void UpdateBook(string title, Bookstore.Interface.Book updatedBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookstoreService/UpdateBook", ReplyAction="http://tempuri.org/IBookstoreService/UpdateBookResponse")]
        System.Threading.Tasks.Task UpdateBookAsync(string title, Bookstore.Interface.Book updatedBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookstoreService/DeleteBook", ReplyAction="http://tempuri.org/IBookstoreService/DeleteBookResponse")]
        void DeleteBook(Bookstore.Interface.Book delBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookstoreService/DeleteBook", ReplyAction="http://tempuri.org/IBookstoreService/DeleteBookResponse")]
        System.Threading.Tasks.Task DeleteBookAsync(Bookstore.Interface.Book delBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookstoreService/UpdateBooks", ReplyAction="http://tempuri.org/IBookstoreService/UpdateBooksResponse")]
        void UpdateBooks(System.Collections.Generic.List<Bookstore.Interface.Book> updatedBooks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookstoreService/UpdateBooks", ReplyAction="http://tempuri.org/IBookstoreService/UpdateBooksResponse")]
        System.Threading.Tasks.Task UpdateBooksAsync(System.Collections.Generic.List<Bookstore.Interface.Book> updatedBooks);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookstoreServiceChannel : BookstoreRef.Service.MyService.IBookstoreService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookstoreServiceClient : System.ServiceModel.ClientBase<BookstoreRef.Service.MyService.IBookstoreService>, BookstoreRef.Service.MyService.IBookstoreService {
        
        public BookstoreServiceClient() {
        }
        
        public BookstoreServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookstoreServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookstoreServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookstoreServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public BookstoreRef.Service.MyService.CompositeType GetDataUsingDataContract(BookstoreRef.Service.MyService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<BookstoreRef.Service.MyService.CompositeType> GetDataUsingDataContractAsync(BookstoreRef.Service.MyService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public System.Collections.Generic.List<Bookstore.Interface.Book> GetBooks() {
            return base.Channel.GetBooks();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Bookstore.Interface.Book>> GetBooksAsync() {
            return base.Channel.GetBooksAsync();
        }
        
        public System.Collections.Generic.List<Bookstore.Interface.Book> GetBookAsync(string searchString, string searchOn) {
            return base.Channel.GetBookAsync(searchString, searchOn);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Bookstore.Interface.Book>> GetBookAsyncAsync(string searchString, string searchOn) {
            return base.Channel.GetBookAsyncAsync(searchString, searchOn);
        }
        
        public void AddBook(Bookstore.Interface.Book newBook) {
            base.Channel.AddBook(newBook);
        }
        
        public System.Threading.Tasks.Task AddBookAsync(Bookstore.Interface.Book newBook) {
            return base.Channel.AddBookAsync(newBook);
        }
        
        public void UpdateBook(string title, Bookstore.Interface.Book updatedBook) {
            base.Channel.UpdateBook(title, updatedBook);
        }
        
        public System.Threading.Tasks.Task UpdateBookAsync(string title, Bookstore.Interface.Book updatedBook) {
            return base.Channel.UpdateBookAsync(title, updatedBook);
        }
        
        public void DeleteBook(Bookstore.Interface.Book delBook) {
            base.Channel.DeleteBook(delBook);
        }
        
        public System.Threading.Tasks.Task DeleteBookAsync(Bookstore.Interface.Book delBook) {
            return base.Channel.DeleteBookAsync(delBook);
        }
        
        public void UpdateBooks(System.Collections.Generic.List<Bookstore.Interface.Book> updatedBooks) {
            base.Channel.UpdateBooks(updatedBooks);
        }
        
        public System.Threading.Tasks.Task UpdateBooksAsync(System.Collections.Generic.List<Bookstore.Interface.Book> updatedBooks) {
            return base.Channel.UpdateBooksAsync(updatedBooks);
        }
    }
}
